### ISSUE TITLE
Update for version 1.59

### ISSUE THREAD

**Issue by Retrieval2967** [MarkusJx/autobet#50]
Would you be so kind as to update autobet for the latest version? I would love to use autobet but unfortunately it doesn't detect my game (Social Club).

**Comment by MarkusJx** [comment]
There is actually no need for autobet to detect your game (in fact, it can't), as it doesn't interact with the executables in any way.
It just takes screenshots and moves your mouse around accoordingly, so you issue is probably something different.
Would you mind sending me some more information about this issue and [some logs](https://github.com/MarkusJx/autobet/wiki/Debugging)?

**Comment by Retrieval2967** [comment]
Thank you for the swift response, it's stuck on initializing, as shown on the screenshot
![autobet_Yfs4XNhuml](https://user-images.githubusercontent.com/104709822/166135113-30edb721-4c47-4fe9-83bd-f92d4d1f0351.png)
Unfortunately, I can't send anything except this screenshot, as the zip file on the desktop is empty, and out.log wasn't generated at it's supposed place. Thank you for the assistance!

**Comment by MarkusJx** [comment]
Uhmm, so, yeah, this is related to the program not starting properly (or rather, the render process throwing some error).
Could you start the program from the command line with the following flag passed ``--enableDevTools`` to enable dev tools, then, press ``CTRL+SHIFT+I`` to open the devtools and send me the errors printed in there (those should be marked red).

## More detailed steps (if you need further instructions)
* Open up a command promp (type in ``cmd`` in your search bar, press enter)
* Change to the directory where your autobet installation (or the shortcut to it) is located using ``cd``, e.g. ``cd Desktop``
* Run the program with the devTools flag: ``autobet.lnk --enableDevTools``

**Comment by Retrieval2967** [comment]
Uncaught (in promise) Error: unable to open database file
d45666d5-b617-4d00-a3b3-dff9d7e7d801:1 Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'file:///C:/Program%20Files/autobet/resources/app.asar/renderer/out/worker-javascript.js' failed to load.
    at blob:file:///d45666d5-b617-4d00-a3b3-dff9d7e7d801:1:1

**Comment by MarkusJx** [comment]
Is that the only issue? Because that one is actually not a problem. If so, try re-installing the program, that may fix your problem.
You are using the latest version (v1.4.0), right?

**Comment by Retrieval2967** [comment]
I am using 1.4.0 and I've also tried reinstalling. Maybe my gpu doesnt support Vulkan? Its an R7 240.

**Comment by MarkusJx** [comment]
I don't see why not having vulkan support would be an issue. Also, I've ran autobet on really old hardware (built in 2010 or so), but those were older versions of autobet...You could try installing v1.3.1 but that one will automatically update to v1.4.0 once restarted, so this would only help us see if this is related to v1.4.0. Did you use autobet before update 1.4.0? As 1.4.0 brought new config options, there may be an issue with that

**Comment by Retrieval2967** [comment]
1,3,1 seems to work for me, it detects my game

**Comment by MarkusJx** [comment]
So the issue is v1.4.0, could you try enabling logging to file (no extended debugging) in v1.3.1, stop the program, wait a few minutes for the update to finish (or just update manually), start up v1.4.0, wait some time, stop that and send me the logs which are stored in ``YOUR_DOCUMENTS_FOLDER/autobet/autobet.log`` (The logs are usually written on program exit)

**Comment by Retrieval2967** [comment]
[autobet.log](https://github.com/MarkusJx/autobet/files/8598484/autobet.log)
Okay so it is indeed the latest version that is causing the issue, here are the logs

**Comment by MarkusJx** [comment]
So I don't see a clear issue in there and I am unable to reproduce this bug, maybe try deleting the config folder (``YOUR_DOCUMENTS_FOLDER/autobet``). Or maybe this is a caching issue with electron. In this case, try deleting the electron directory, which is located in ``C:\Users\<user>\AppData\Roaming\autobet``. If nothing helps, I could offer you an installer of version 1.3.1 with automatic updates disabled.

**Comment by Retrieval2967** [comment]
Actually, my bad, here are the latest log files, after I enabled the log to file option. Could you take a look if this is any different? Thank you so much for the help.
[autobet.log](https://github.com/MarkusJx/autobet/files/8598502/autobet.log)
:

**Comment by MarkusJx** [comment]
Nope, still nothing, I'd suggest trying to delete the cache(s), as there are no signs of errors, which is weird

**Comment by Retrieval2967** [comment]
I've tried deleting both cache folders, unfortunately it didn't bring any success. Could you please make an installer of 1.3.1 without auto updates? Also, is there any difference in the betting algorithm between 1.3.1 and 1.4.0?

**Comment by MarkusJx** [comment]
I've added the version without automatic updates to [the release section of v1.3.1](https://github.com/MarkusJx/autobet/releases/download/v1.3.1/autobet-v1.3.1-no-autoupdate.exe).

And no, there were no changes regarding the betting algorithm in v1.4.0 made, that algorithm is the same since v1.1.0.
v1.4.0 mainly brought UI changes, a better web ui with SSL and (browser) Notification support, support for collecting historic data, plus some configuration options, so nothing, which impacts the profit, generated by this tool.

But anyways, I'm really sorry I couldn't (properly) help you with this issue and I hope that I can find a solution to this, at some point. If you find any new clues, please let me know, maybe we can find something to work with.

Cheers! :)

**Comment by Retrieval2967** [comment]
Thank you so much for your efforts, I'm really grateful for your assistance!
