### ISSUE TITLE
Window isn't detected if its name contains non utf-8 characters

### ISSUE THREAD

**Issue by MarkusJx** [MarkusJx/autobet#59]
The game is detected as non-running if the windows name contains non utf-8 characters.
This is not an issue with vanilla GTA 5, but with FiveM, as those window names may contain emojis and other characters.

See also [this comment](https://github.com/MarkusJx/autobet/discussions/58#discussioncomment-4448770).

**Comment by ShyRoxxx** [comment]
Status?

**Comment by MarkusJx** [comment]
See this: https://github.com/MarkusJx/autobet/discussions/58#discussioncomment-4470525

**Comment by MarkusJx** [comment]
Any further updates will be posted in here.

**Comment by ShyRoxxx** [comment]
👍
